# Generated by Django 4.2.11 on 2026-02-03 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'created'), ('pending', 'pending'), ('processed', 'processed'), ('failed', 'failed')], default='created', max_length=12)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('client_request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx')],
            },
        ),
    ]
